//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BettorKnow.PremierStatisticsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FixtureDto", Namespace="http://schemas.datacontract.org/2004/07/PremierStatisticsLib.Dto")]
    [System.SerializableAttribute()]
    public partial class FixtureDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BettorKnow.PremierStatisticsService.TeamDto AwayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BettorKnow.PremierStatisticsService.TeamDto HomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MatchDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BettorKnow.PremierStatisticsService.TeamDto Away {
            get {
                return this.AwayField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayField, value) != true)) {
                    this.AwayField = value;
                    this.RaisePropertyChanged("Away");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BettorKnow.PremierStatisticsService.TeamDto Home {
            get {
                return this.HomeField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeField, value) != true)) {
                    this.HomeField = value;
                    this.RaisePropertyChanged("Home");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MatchDate {
            get {
                return this.MatchDateField;
            }
            set {
                if ((this.MatchDateField.Equals(value) != true)) {
                    this.MatchDateField = value;
                    this.RaisePropertyChanged("MatchDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamDto", Namespace="http://schemas.datacontract.org/2004/07/PremierStatisticsLib.Dto")]
    [System.SerializableAttribute()]
    public partial class TeamDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PremierStatisticsService.IPremierStatistics")]
    public interface IPremierStatistics {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/Fixtures", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesResponse")]
        BettorKnow.PremierStatisticsService.FixtureDto[] Fixtures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/Fixtures", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesResponse")]
        System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesByDate", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesByDateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.TeamDto))]
        BettorKnow.PremierStatisticsService.FixtureDto[] FixturesByDate(object dateRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesByDate", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesByDateResponse")]
        System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesByDateAsync(object dateRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesByTeam", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesByTeamResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.TeamDto))]
        BettorKnow.PremierStatisticsService.FixtureDto[] FixturesByTeam(object team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesByTeam", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesByTeamResponse")]
        System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesByTeamAsync(object team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesByDateTeam", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesByDateTeamResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.TeamDto))]
        BettorKnow.PremierStatisticsService.FixtureDto[] FixturesByDateTeam(object dateRange, object team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesByDateTeam", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesByDateTeamResponse")]
        System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesByDateTeamAsync(object dateRange, object team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesForTeamCurrentWeek", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesForTeamCurrentWeekResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.FixtureDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BettorKnow.PremierStatisticsService.TeamDto))]
        BettorKnow.PremierStatisticsService.FixtureDto[] FixturesForTeamCurrentWeek(object team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesForTeamCurrentWeek", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesForTeamCurrentWeekResponse")]
        System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesForTeamCurrentWeekAsync(object team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesForCurrentWeek", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesForCurrentWeekResponse")]
        BettorKnow.PremierStatisticsService.FixtureDto[] FixturesForCurrentWeek();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPremierStatistics/FixturesForCurrentWeek", ReplyAction="http://tempuri.org/IPremierStatistics/FixturesForCurrentWeekResponse")]
        System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesForCurrentWeekAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPremierStatisticsChannel : BettorKnow.PremierStatisticsService.IPremierStatistics, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PremierStatisticsClient : System.ServiceModel.ClientBase<BettorKnow.PremierStatisticsService.IPremierStatistics>, BettorKnow.PremierStatisticsService.IPremierStatistics {
        
        public PremierStatisticsClient() {
        }
        
        public PremierStatisticsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PremierStatisticsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremierStatisticsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremierStatisticsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BettorKnow.PremierStatisticsService.FixtureDto[] Fixtures() {
            return base.Channel.Fixtures();
        }
        
        public System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesAsync() {
            return base.Channel.FixturesAsync();
        }
        
        public BettorKnow.PremierStatisticsService.FixtureDto[] FixturesByDate(object dateRange) {
            return base.Channel.FixturesByDate(dateRange);
        }
        
        public System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesByDateAsync(object dateRange) {
            return base.Channel.FixturesByDateAsync(dateRange);
        }
        
        public BettorKnow.PremierStatisticsService.FixtureDto[] FixturesByTeam(object team) {
            return base.Channel.FixturesByTeam(team);
        }
        
        public System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesByTeamAsync(object team) {
            return base.Channel.FixturesByTeamAsync(team);
        }
        
        public BettorKnow.PremierStatisticsService.FixtureDto[] FixturesByDateTeam(object dateRange, object team) {
            return base.Channel.FixturesByDateTeam(dateRange, team);
        }
        
        public System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesByDateTeamAsync(object dateRange, object team) {
            return base.Channel.FixturesByDateTeamAsync(dateRange, team);
        }
        
        public BettorKnow.PremierStatisticsService.FixtureDto[] FixturesForTeamCurrentWeek(object team) {
            return base.Channel.FixturesForTeamCurrentWeek(team);
        }
        
        public System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesForTeamCurrentWeekAsync(object team) {
            return base.Channel.FixturesForTeamCurrentWeekAsync(team);
        }
        
        public BettorKnow.PremierStatisticsService.FixtureDto[] FixturesForCurrentWeek() {
            return base.Channel.FixturesForCurrentWeek();
        }
        
        public System.Threading.Tasks.Task<BettorKnow.PremierStatisticsService.FixtureDto[]> FixturesForCurrentWeekAsync() {
            return base.Channel.FixturesForCurrentWeekAsync();
        }
    }
}
